SELECT
    CHR(83),
    CHR(115)
FROM
dual;

-------------

SELECT
     CHR(NULL)
 FROM
     DUAL;

-----------

SELECT
        first_name || '' ||  last_name ||
CHR(9) || 'JOINED ON' || CHR(9) ||

to_char(hire_date, 'DD-MON-YYYY') first_5_employees
FROM
        ADMIN.employees
ORDER BY
        hire_date
FETCH
        FIRST 5 ROWS ONLY;


-----------------------ORACLE CONCAT-----------------------

SELECT
    CONCAT('Happy', 'coding')
FROM
    dual;

--------------

SELECT
        CONCAT(CONCAT('Happy', 'coding'), 'together')
FROM
        dual;

----------------

SELECT
        'Happy'|| 'coding' || 'together'
FROM
        dual;

------------

SELECT
        CONCAT('let''s', 'try this')
FROM
        dual;

----------------------------------------------------------INSTR FUNCTION-----------------------------------------------------

SELECT
        INSTR( 'This is a playlist', 'is') substring_location
FROM
        dual;

--------------------

SELECT
    INSTR( 'This is a playlist', 'is', 1, 2) second_occurrence,
    INSTR( 'This is a playlist', 'is', 1, 3) third_occurrence
FROM
    dual;

--------------

SELECT
        INSTR( 'This is a playlist', 'are') substring_location
FROM
        dual;

-------------

SELECT
        INSTR( 'This is a playlist', 'is',-1) substring_location
FROM
        dual;

-----------------------------------------------ORACLE INITCAP--------------------------------------------

SELECT
        INITCAP('hi john')
FROM
        DUAL;

-----------------

SELECT
        INITCAP( first_name || ' ' || last_name ) full_name
FROM
        admin.contacts
ORDER BY
        full_name;

----------------------------------------------------ORACLE LENGTH()--------------------------------------------------------

SELECT
        'Oracle LENGTH' string,
        LENGTH('Oracle LENGTH') Len
FROM
        dual;

-----------------

SELECT
        first_name,
        LENGTH(first_name)
FROM
        ADMIN.employees
ORDER BY
        LENGTH(first_name) DESC;

-------------------

SELECT
        LENGTH(first_name) len,
        COUNT(*)
FROM
        ADMIN.employees
GROUP BY
        LENGTH(first_name)
ORDER BY len;

------------------

SELECT
product_name,
CASE
        WHEN LENGTH( description ) > 50 THEN CONCAT (SUBSTR(description,
1, 58),'...')
ELSE description
END product_excerpt
FROM
        ADMIN.products
ORDER BY
        product_name;

-----------------------------------------------ORACLE LTRIM---------------------------------------------

SELECT
        product_name
FROM
        ADMIN.products
WHERE
        product_name LIKE 'ASRock%'
ORDER BY
        product_name;

----------------------------

SELECT
product_name,
LTRIM( product_name, 'ASRock') short_product_name
FROM
ADMIN.products
WHERE
product_name LIKE 'ASRock%'
ORDER BY
product_name;

-------------------------------ORACLE REPLACE-----------------------------------

CREATE TABLE articles (
        article_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
        title VARCHAR2(255),
        article_body VARCHAR2(4000),
        PRIMARY KEY (article_id)
);

INSERT INTO articles (title, article_body)
VALUES('Sample article', 'This is a <strong>sample</strong> article');
INSERT INTO articles (title, article_body)
VALUES('Another article', 'Another excellent <strong>sample</strong> article');

SELECT
        article_id, title, article_body
FROM
        articles;

------------------------------------
UPDATE
articles
SET
article_body = REPLACE (article_body, '<strong>', '<b>');
UPDATE
articles
SET
article_body = REPLACE (article_body, '</strong>', '</b>');

--------------------------------











